import { BadRequestException, Injectable, NotFoundException } from '@nestjs/common'; import { Prisma } from '@prisma/client'; import { PrismaService } from '../../prisma/prisma.service'; import { normalizeIranPhone } from '../../common/phone'; import { safeLimit } from '../../common/pagination'; import { CreateInvoiceDto,InvoiceLineDto } from './dto'; import { InvoiceRenderService } from './invoice-render.service'; import { EntitlementsService } from '../entitlements/entitlements.service';
@Injectable() export class InvoicesService {
 constructor(private readonly prisma:PrismaService,private readonly renderer:InvoiceRenderService,private readonly entitlements:EntitlementsService){}
 async create(businessId:string,creatorId:string,d:CreateInvoiceDto){const monthly=await this.prisma.invoice.count({where:{businessId,createdAt:{gte:this.entitlements.monthStart()}}});await this.entitlements.assertCount(businessId,'invoices','monthly_invoices',monthly);let phone:string;try{phone=normalizeIranPhone(d.customerPhone)}catch{throw new BadRequestException({code:'INVALID_PHONE',message:'شماره مشتری معتبر نیست'})};const customer=await this.prisma.user.findUnique({where:{phone},include:{profile:true}});if(!customer)throw new BadRequestException({code:'CUSTOMER_NOT_REGISTERED',message:'این شماره هنوز در کاربان ثبت‌نام نکرده است',details:{canInvite:true}});if(customer.status!=='ACTIVE')throw new BadRequestException({code:'CUSTOMER_UNAVAILABLE',message:'حساب مشتری فعال نیست'});const business=await this.prisma.business.findUnique({where:{id:businessId}});if(!business)throw new NotFoundException({code:'BUSINESS_NOT_FOUND',message:'کسب‌وکار پیدا نشد'});if(!d.items.length)throw new BadRequestException({code:'EMPTY_INVOICE',message:'حداقل یک قلم لازم است'});
  const resolved=await Promise.all(d.items.map(x=>this.resolveLine(businessId,x)));const subtotal=resolved.reduce((s,x)=>s+x.base,0n);const tax=resolved.reduce((s,x)=>s+x.tax,0n);const discount=BigInt(d.invoiceDiscountRial??0)+resolved.reduce((s,x)=>s+x.discount,0n);const shipping=BigInt(d.shippingRial??0);const total=subtotal-discount+tax+shipping;if(total<0n)throw new BadRequestException({code:'INVALID_TOTAL',message:'مبلغ نهایی نامعتبر است'});
  return this.prisma.$transaction(async tx=>{await tx.$executeRaw`SELECT pg_advisory_xact_lock(hashtext(${businessId}))`;const count=await tx.invoice.count({where:{businessId}});const year=new Intl.DateTimeFormat('en-US-u-ca-persian',{year:'numeric'}).format(new Date());const invoiceNo=`${year}-${String(count+1).padStart(6,'0')}`;const invoice=await tx.invoice.create({data:{businessId,customerId:customer.id,invoiceNo,status:'ISSUED',issuedAt:new Date(),dueAt:d.dueAt?new Date(d.dueAt):undefined,subtotalRial:subtotal,discountRial:discount,taxRial:tax,shippingRial:shipping,totalRial:total,notes:d.notes,createdById:creatorId,sellerSnapshot:{name:business.name,phone:business.phone,address:business.address,nationalId:business.nationalId,economicCode:business.economicCode,logoUrl:business.logoUrl,signatureUrl:business.signatureUrl,stampUrl:business.stampUrl},customerSnapshot:{id:customer.id,phone:customer.phone,name:customer.profile?.displayName??null},paymentSnapshot:{bankCardMasked:business.bankCardMasked,ibanMasked:business.ibanMasked,instructions:business.paymentInstructions},items:{create:resolved.map((x,i)=>({...x.data,sortOrder:i}))}} ,include:{items:true}});for(const line of resolved){if(!line.data.inventoryItemId)continue;const item=await tx.inventoryItem.findUniqueOrThrow({where:{id:line.data.inventoryItemId}});const qty=line.data.quantity as Prisma.Decimal;if(item.currentQty.lessThan(qty))throw new BadRequestException({code:'INSUFFICIENT_STOCK',message:`موجودی ${item.name} کافی نیست`});const after=item.currentQty.minus(qty);await tx.inventoryItem.update({where:{id:item.id},data:{currentQty:after}});await tx.inventoryMovement.create({data:{businessId,inventoryItemId:item.id,type:'SALE',quantity:qty,unitCostRial:item.averageCostRial,referenceType:'INVOICE',referenceId:invoice.id,reason:`صورتحساب ${invoiceNo}`,createdById:creatorId,metadata:{before:item.currentQty.toString(),after:after.toString()}}})}await tx.notification.create({data:{userId:customer.id,businessId,type:'INVOICE_ISSUED',title:'صورتحساب جدید',body:`${business.name} صورتحساب ${invoiceNo} را برای شما صادر کرد.`,route:`/invoices/${invoice.id}`,metadata:{invoiceId:invoice.id}}});return invoice});
 }
 private async resolveLine(businessId:string,x:InvoiceLineDto){let title=x.title??'';let description=x.description;let unit=x.unitLabel??'عدد';let unitPrice=BigInt(x.unitPriceRial??0);let taxBp=x.taxRateBasisPoints??0;let taxId=x.taxProductServiceId;let serviceId:string|undefined;let inventoryItemId:string|undefined;let snapshot:Prisma.InputJsonValue|undefined;
  if(x.type==='SERVICE'){if(!x.serviceId)throw new BadRequestException({code:'SERVICE_REQUIRED',message:'خدمت انتخاب نشده'});const s=await this.prisma.service.findFirst({where:{id:x.serviceId,businessId,active:true}});if(!s)throw new BadRequestException({code:'SERVICE_NOT_FOUND',message:'خدمت پیدا نشد'});title=s.name;description=x.description??s.description??undefined;unit=s.unitLabel;unitPrice=s.priceRial;taxBp=s.taxRateBasisPoints;taxId=s.taxProductServiceId??undefined;serviceId=s.id;snapshot={name:s.name,priceRial:s.priceRial.toString()};}
  if(x.type==='INVENTORY'){if(!x.inventoryItemId)throw new BadRequestException({code:'INVENTORY_REQUIRED',message:'کالای انبار انتخاب نشده'});const item=await this.prisma.inventoryItem.findFirst({where:{id:x.inventoryItemId,businessId,active:true}});if(!item||item.salePriceRial==null)throw new BadRequestException({code:'INVENTORY_NOT_SELLABLE',message:'قلم انبار قابل فروش نیست'});title=item.name;description=x.description??item.description??undefined;unit=item.unit;unitPrice=item.salePriceRial;taxBp=item.taxRateBasisPoints;taxId=item.taxProductServiceId??undefined;inventoryItemId=item.id;snapshot={name:item.name,sku:item.sku,salePriceRial:item.salePriceRial.toString()};}
  if(x.type==='CUSTOM'&&(!title||x.unitPriceRial==null))throw new BadRequestException({code:'CUSTOM_LINE_INVALID',message:'شرح و مبلغ قلم آزاد الزامی است'});const q=new Prisma.Decimal(x.quantity);const gross=BigInt(q.mul(unitPrice.toString()).toDecimalPlaces(0).toString());const discount=BigInt(x.discountRial??0);if(discount>gross)throw new BadRequestException({code:'LINE_DISCOUNT_INVALID',message:'تخفیف قلم بیش از مبلغ آن است'});const taxable=gross-discount;const tax=(taxable*BigInt(taxBp))/10000n;const lineTotal=taxable+tax;return{base:gross,tax,discount,data:{type:x.type,serviceId,inventoryItemId,title,description,quantity:q,unitLabel:unit,unitPriceRial:unitPrice,discountRial:discount,taxRateBasisPoints:taxBp,taxRial:tax,lineTotalRial:lineTotal,taxProductServiceId:taxId,snapshot}};}
 async customerList(userId:string,cursor?:string,limit?:number){const take=safeLimit(limit,20,50);const rows=await this.prisma.invoice.findMany({where:{customerId:userId},take:take+1,...(cursor?{cursor:{id:cursor},skip:1}:{}),orderBy:{createdAt:'desc'},include:{business:{select:{name:true,slug:true,logoUrl:true}},renders:{where:{status:'READY',expiresAt:{gt:new Date()}},orderBy:{createdAt:'desc'},take:2}}});const hasNextPage=rows.length>take;const items=rows.slice(0,take);return{items,pageInfo:{hasNextPage,nextCursor:hasNextPage?items.at(-1)?.id??null:null}}}
 async businessList(businessId:string,cursor?:string,limit?:number,status?:string){const take=safeLimit(limit,30,100);const rows=await this.prisma.invoice.findMany({where:{businessId,...(status?{status:status as never}:{})},take:take+1,...(cursor?{cursor:{id:cursor},skip:1}:{}),orderBy:{createdAt:'desc'},include:{customer:{include:{profile:true}}}});const hasNextPage=rows.length>take;const items=rows.slice(0,take);return{items,pageInfo:{hasNextPage,nextCursor:hasNextPage?items.at(-1)?.id??null:null}}}
 async render(invoiceId:string,format:'PDF'|'PNG'){return this.renderer.render(invoiceId,format)}
}
