[package]
name = "karban-mobile"
version = "0.1.0"
description = "Karban mobile client"
edition = "2021"

[lib]
name = "karban_mobile_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-deep-link = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
