import type{ButtonHTMLAttributes,InputHTMLAttributes,ReactNode}from'react';import{Icon,type IconName}from'../design/Icon';
export function Screen({children,className=''}:{children:ReactNode;className?:string}){return <main className={`screen ${className}`}>{children}</main>}
export function PageHeader({title,subtitle,back,onBack,action}:{title:string;subtitle?:string;back?:boolean;onBack?:()=>void;action?:ReactNode}){return <header className="page-head"><div className="page-head-row">{back?<button className="icon-btn" onClick={onBack}><Icon name="back"/></button>:null}<div className="page-head-copy"><h1>{title}</h1>{subtitle?<p>{subtitle}</p>:null}</div>{action}</div></header>}
export function Button({children,icon,loading=false,variant='primary',...props}:ButtonHTMLAttributes<HTMLButtonElement>&{icon?:IconName;loading?:boolean;variant?:'primary'|'secondary'|'ghost'|'danger'}){return <button {...props} disabled={props.disabled||loading} className={`btn btn-${variant} ${props.className??''}`}>{loading?<span className="spinner"/>:icon?<Icon name={icon} size={18}/>:null}<span>{children}</span></button>}
export function Input({label,hint,...props}:InputHTMLAttributes<HTMLInputElement>&{label?:string;hint?:string}){return <label className="field">{label?<span>{label}</span>:null}<input {...props}/>{hint?<small>{hint}</small>:null}</label>}
export function Card({children,className=''}:{children:ReactNode;className?:string}){return <section className={`card ${className}`}>{children}</section>}
export function Empty({title,body,icon='invoice',action}:{title:string;body?:string;icon?:IconName;action?:ReactNode}){return <div className="empty"><span className="empty-icon"><Icon name={icon} size={28}/></span><h3>{title}</h3>{body?<p>{body}</p>:null}{action}</div>}
export function Skeleton({className=''}:{className?:string}){return <div className={`skeleton ${className}`}/>}
export function StatusBadge({children,tone='neutral'}:{children:ReactNode;tone?:'neutral'|'good'|'warn'|'bad'|'info'}){return <span className={`status status-${tone}`}>{children}</span>}
