import { useMemo, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { Button, Card, Input, PageHeader, Screen } from '../components/ui';
import { post, ApiError, patch, uploadFile } from '../lib/api';

type Draft={name:string;slug:string;username:string;bio:string;phone:string;province:string;city:string;address:string;latitude?:number;longitude?:number};
type AssetKey='logoUrl'|'signatureUrl'|'stampUrl';
const empty:Draft={name:'',slug:'',username:'',bio:'',phone:'',province:'',city:'',address:''};
const steps=[['intro','شروع'],['profile','معرفی'],['location','موقعیت'],['branding','هویت بصری'],['payments','پرداخت'],['done','پایان']]as const;

export function StartBusinessPage(){
  const nav=useNavigate();const[index,setIndex]=useState(0);const[draft,setDraft]=useState<Draft>(empty);const[loading,setLoading]=useState(false);const[error,setError]=useState('');const[assets,setAssets]=useState<Partial<Record<AssetKey,File>>>({});const[needBrandHelp,setNeedBrandHelp]=useState(false);const[cardNumber,setCardNumber]=useState('');const[iban,setIban]=useState('');const[paymentNote,setPaymentNote]=useState('');
  const step=steps[index]?.[0]??'done';const pct=Math.round(((index+1)/steps.length)*100);const canNext=useMemo(()=>step==='profile'?Boolean(draft.name&&draft.slug):true,[step,draft]);
  async function finish(){setLoading(true);setError('');try{const b=await post<{id:string}>('/businesses',draft);const profilePatch:Record<string,string>={};for(const key of ['logoUrl','signatureUrl','stampUrl'] as AssetKey[]){const file=assets[key];if(!file)continue;const uploaded=await uploadFile(file,{purpose:key,businessId:b.id,visibility:'PUBLIC'});profilePatch[key]=uploaded.url}if(paymentNote)profilePatch.paymentInstructions=paymentNote;if(Object.keys(profilePatch).length)await patch(`/businesses/${b.id}`,profilePatch);if(cardNumber.trim())await post(`/payments/business/${b.id}/methods`,{type:'CARD',label:'کارت بانکی',isDefault:true,publicDetails:{cardNumber:cardNumber.replace(/\D/g,'')}});if(iban.trim())await post(`/payments/business/${b.id}/methods`,{type:'IBAN',label:'شماره شبا',publicDetails:{iban:iban.replace(/\s/g,'').toUpperCase()}});if(needBrandHelp)await post('/reports',{targetType:'BUSINESS',targetId:b.id,businessId:b.id,category:'BUSINESS_BRANDING_HELP',description:'مالک هنگام راه‌اندازی برای آماده‌سازی لوگو، مهر یا امضای صورتحساب درخواست کمک کرده است.'});nav(`/business/${b.id}/dashboard`,{replace:true})}catch(e){setError(e instanceof ApiError?e.message:'ثبت کسب‌وکار ناموفق بود')}finally{setLoading(false)}}
  function next(){if(index<steps.length-1)setIndex(v=>v+1);else void finish()}
  function geo(){navigator.geolocation?.getCurrentPosition(p=>setDraft(d=>({...d,latitude:p.coords.latitude,longitude:p.coords.longitude})),()=>setError('دسترسی به موقعیت داده نشد'))}
  const assetInput=(key:AssetKey,label:string)=><label className="upload-row"><div><b>{label}</b><span>{assets[key]?.name??'فایل انتخاب نشده'}</span></div><input type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>setAssets(a=>({...a,[key]:e.target.files?.[0]}))}/><Button type="button" variant="secondary">انتخاب فایل</Button></label>;
  return <Screen className="wizard"><PageHeader title="ساخت پروفایل کسب‌وکار" subtitle={`مرحله ${index+1} از ${steps.length}`} back onBack={()=>index?setIndex(v=>v-1):nav(-1)}/><div className="progress"><i style={{width:`${pct}%`}}/></div>
    {step==='intro'?<Card className="wizard-card"><span className="eyebrow">برای متخصص‌ها</span><h2>کسب‌وکار شما، حرفه‌ای و قابل اعتماد</h2><p>پروفایل عمومی، صورتحساب، انبار، کیف پول و پیامک را قدم‌به‌قدم آماده می‌کنیم. هر بخشی را که الان آماده ندارید بعداً می‌توانید تکمیل کنید.</p><ul className="check-list"><li>مشتری‌ها با جستجو شما را پیدا می‌کنند</li><li>خدمات و قیمت‌ها قبل از صدور صورتحساب تعریف می‌شوند</li><li>لوگو، امضا و مهر روی نسخه رسمی صورتحساب قرار می‌گیرند</li></ul></Card>:null}
    {step==='profile'?<Card className="wizard-card"><Input label="نام کسب‌وکار" value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/><Input label="شناسه لینک" hint="فقط حروف انگلیسی، عدد و خط تیره" dir="ltr" value={draft.slug} onChange={e=>setDraft({...draft,slug:e.target.value.toLowerCase().replace(/[^a-z0-9-]/g,'')})}/><Input label="نام کاربری" dir="ltr" value={draft.username} onChange={e=>setDraft({...draft,username:e.target.value})}/><label className="field"><span>معرفی کوتاه</span><textarea value={draft.bio} onChange={e=>setDraft({...draft,bio:e.target.value})}/></label><Input label="شماره تماس کاری" inputMode="tel" dir="ltr" value={draft.phone} onChange={e=>setDraft({...draft,phone:e.target.value})}/></Card>:null}
    {step==='location'?<Card className="wizard-card"><Input label="استان" value={draft.province} onChange={e=>setDraft({...draft,province:e.target.value})}/><Input label="شهر" value={draft.city} onChange={e=>setDraft({...draft,city:e.target.value})}/><label className="field"><span>نشانی</span><textarea value={draft.address} onChange={e=>setDraft({...draft,address:e.target.value})}/></label><Button variant="secondary" icon="location" onClick={geo}>استفاده از موقعیت فعلی</Button></Card>:null}
    {step==='branding'?<Card className="wizard-card"><h2>لوگو، امضا و مهر</h2><p>فایل‌های انتخاب‌شده بعد از ساخت کسب‌وکار آپلود و به پروفایل متصل می‌شوند. اگر آماده ندارید، رد کنید و برای کمک درخواست ثبت کنید.</p>{assetInput('logoUrl','لوگو')}{assetInput('signatureUrl','امضا')}{assetInput('stampUrl','مهر')}<label className="switch-row"><input type="checkbox" checked={needBrandHelp} onChange={e=>setNeedBrandHelp(e.target.checked)}/><span>برای آماده‌سازی هویت بصری و فایل‌های صورتحساب از سیستم کمک می‌خواهم</span></label></Card>:null}
    {step==='payments'?<Card className="wizard-card"><h2>روش دریافت پول</h2><p>این اطلاعات در صورت فعال‌بودن روی صورتحساب نمایش داده می‌شوند. درگاه آنلاین زرین‌پال توسط مدیر سیستم پیکربندی می‌شود.</p><Input label="شماره کارت دریافت" dir="ltr" inputMode="numeric" value={cardNumber} onChange={e=>setCardNumber(e.target.value)}/><Input label="شماره شبا" dir="ltr" value={iban} onChange={e=>setIban(e.target.value)}/><label className="field"><span>توضیح پرداخت برای مشتری</span><textarea value={paymentNote} onChange={e=>setPaymentNote(e.target.value)}/></label></Card>:null}
    {step==='done'?<Card className="wizard-card"><h2>برای شروع آماده‌اید</h2><p>بعد از ساخت پروفایل، اول دسته‌ها و خدمات را تعریف کنید؛ سپس انبار را تکمیل کنید و اولین صورتحساب را بسازید.</p>{error?<p className="form-error">{error}</p>:null}</Card>:null}
    <div className="wizard-footer"><Button disabled={!canNext} loading={loading} onClick={next}>{step==='done'?'ساخت کسب‌وکار':'ادامه'}</Button>{['branding','payments'].includes(step)?<button className="text-action" onClick={next}>فعلاً رد می‌کنم</button>:null}</div>
  </Screen>;
}
