import { useQuery } from '@tanstack/react-query';
import { useState } from 'react';
import { Badge, PageHeader } from '../components/ui';
import { DataTable, type Column } from '../components/DataTable';
import { PaginationBar } from '../components/PaginationBar';
import { api } from '../lib/api';
import { date, rial } from '../lib/format';
type Payment={id:string;providerKey:string;purpose:string;status:string;amountRial:string;authority:string|null;referenceId:string|null;createdAt:string;verifiedAt:string|null;business:{name:string}|null;invoice:{invoiceNo:string}|null};type Page={items:Payment[];pageInfo:{hasNextPage:boolean;nextCursor:string|null}};
const statusFa:Record<string,string>={CREATED:'ایجادشده',REDIRECTED:'ارسال به درگاه',VERIFYING:'در حال بررسی',SUCCEEDED:'موفق',FAILED:'ناموفق',CANCELLED:'لغوشده',REFUNDED:'بازگشت وجه'};
export function PaymentsAdminPage(){const[status,setStatus]=useState('');const[purpose,setPurpose]=useState('');const[cursor,setCursor]=useState<string|undefined>();const data=useQuery({queryKey:['admin-payments',status,purpose,cursor],queryFn:()=>api<Page>(`/admin/payments?status=${encodeURIComponent(status)}&purpose=${encodeURIComponent(purpose)}${cursor?`&cursor=${cursor}`:''}`)});const cols:Column<Payment>[]=[{key:'provider',title:'درگاه',render:r=><div className="cell-main"><b>{r.providerKey}</b><span>{r.purpose}</span></div>},{key:'owner',title:'مرجع',render:r=><div className="cell-main"><b>{r.business?.name??'کیف پول مشتری'}</b><span>{r.invoice?.invoiceNo??'—'}</span></div>},{key:'amount',title:'مبلغ',render:r=>rial(r.amountRial)},{key:'status',title:'وضعیت',render:r=><Badge tone={r.status==='SUCCEEDED'?'good':r.status==='FAILED'||r.status==='CANCELLED'?'bad':'info'}>{statusFa[r.status]??r.status}</Badge>},{key:'authority',title:'Authority / Ref',render:r=><div className="cell-main"><span className="mono">{r.authority??'—'}</span><span className="mono">{r.referenceId??'—'}</span></div>},{key:'created',title:'زمان',render:r=>date(r.verifiedAt??r.createdAt)}];return<><PageHeader title="پرداخت‌ها" subtitle="وضعیت موفق فقط از Verify سمت سرور می‌آید؛ پنل اجازه علامت‌زدن دستی پرداخت به‌عنوان موفق را نمی‌دهد." actions={<><select className="page-search" value={purpose} onChange={e=>{setPurpose(e.target.value);setCursor(undefined)}}><option value="">همه کاربردها</option><option value="WALLET_CHARGE">شارژ کیف پول</option><option value="INVOICE">پرداخت صورتحساب</option><option value="PAYMENT_PLAN">خرید پلن</option></select><select className="page-search" value={status} onChange={e=>{setStatus(e.target.value);setCursor(undefined)}}><option value="">همه وضعیت‌ها</option>{Object.entries(statusFa).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></>}/><DataTable rows={data.data?.items??[]} columns={cols}/><PaginationBar canNext={Boolean(data.data?.pageInfo.hasNextPage)} onNext={()=>{const n=data.data?.pageInfo.nextCursor;if(n)setCursor(n)}} onReset={()=>setCursor(undefined)}/></>}
