import { ForbiddenException, HttpException, HttpStatus, Injectable } from '@nestjs/common';
import { FeatureStatus, OverrideScope, Prisma } from '@prisma/client';
import { PrismaService } from '../../prisma/prisma.service';

type Context={businessTypeId:string;planId:string|null;planKey:string|null;planName:string|null};
@Injectable()
export class EntitlementsService{
  constructor(private readonly p:PrismaService){}
  private async context(businessId:string):Promise<Context>{const b=await this.p.business.findUnique({where:{id:businessId},select:{businessTypeId:true,subscriptions:{where:{active:true,OR:[{endsAt:null},{endsAt:{gt:new Date()}}]},orderBy:{startsAt:'desc'},take:1,include:{plan:true}}}});if(!b)throw new ForbiddenException({code:'BUSINESS_NOT_FOUND',message:'کسب‌وکار پیدا نشد'});const s=b.subscriptions[0];return{businessTypeId:b.businessTypeId,planId:s?.planId??null,planKey:s?.plan.key??null,planName:s?.plan.nameFa??null}}
  private active(o:{expiresAt:Date|null}){return !o.expiresAt||o.expiresAt>new Date()}
  async resolve(businessId:string,key:string){const ctx=await this.context(businessId);const feature=await this.p.feature.findUnique({where:{key},include:{overrides:true}});if(!feature)return{enabled:false,status:'DISABLED' as FeatureStatus,limitOverrides:null,ctx};const candidates:Array<[OverrideScope,string|null]>=[['BUSINESS',businessId],['BUSINESS_TYPE',ctx.businessTypeId],['PLAN',ctx.planId]];for(const[scope,id]of candidates){if(!id)continue;const o=feature.overrides.find(x=>x.scope===scope&&x.scopeId===id&&this.active(x));if(o)return{enabled:o.status==='ENABLED',status:o.status,limitOverrides:o.limits as Record<string,unknown>|null,featureId:feature.id,ctx}}return{enabled:feature.status==='ENABLED',status:feature.status,limitOverrides:null,featureId:feature.id,ctx}}
  async assertFeature(businessId:string,key:string){const r=await this.resolve(businessId,key);if(!r.enabled)throw new ForbiddenException({code:'FEATURE_UNAVAILABLE',message:'این قابلیت برای کسب‌وکار شما فعال نیست',details:{feature:key,status:r.status,planKey:r.ctx.planKey}});return r}
  async limit(businessId:string,featureKey:string,limitKey:string):Promise<{limit:bigint|null;planKey:string|null;planName:string|null}>{const r=await this.assertFeature(businessId,featureKey);const override=r.limitOverrides?.[limitKey];if(typeof override==='number'||typeof override==='string'||typeof override==='bigint')return{limit:BigInt(override),planKey:r.ctx.planKey,planName:r.ctx.planName};if(!r.ctx.planId||!r.featureId)return{limit:null,planKey:r.ctx.planKey,planName:r.ctx.planName};const pl=await this.p.planLimit.findUnique({where:{planId_featureId_limitKey:{planId:r.ctx.planId,featureId:r.featureId,limitKey}}});return{limit:pl?.enabled&&pl.limitValue!=null?pl.limitValue:null,planKey:r.ctx.planKey,planName:r.ctx.planName}}
  async assertCount(businessId:string,featureKey:string,limitKey:string,current:bigint|number){const x=await this.limit(businessId,featureKey,limitKey);if(x.limit!=null&&BigInt(current)>=x.limit)throw new HttpException({code:'PLAN_LIMIT_REACHED',message:'سقف این قابلیت در پلن فعلی تکمیل شده است',details:{feature:featureKey,limitKey,limit:x.limit.toString(),current:String(current),planKey:x.planKey,planName:x.planName,upgradeRequired:true}},HttpStatus.PAYMENT_REQUIRED);return x}
  monthStart(){const n=new Date();return new Date(Date.UTC(n.getUTCFullYear(),n.getUTCMonth(),1))}
}
